### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

### ISSUE THREAD

**Issue by wrz57661** [SeanAvery/yolov5-tensorrt#12]
Hello,SceanAvery! When I run the demo.py,something went wrong.How can I solve it?
File "demo.py", line 23, in main
    processor = Processor(model=args['model'])
  File "/home/waveshare/yolov5-tensorrt/python/lib/Processor.py", line 19, in __init__
    self.context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

**Comment by SeanAvery** [comment]
hey @wrz57661 , this is due to differing TRT version from the compiled model. 

I have updated the `export_tensorrt.py` script.

Will work if you recompile.

**Comment by SeanAvery** [comment]
uploaded new compiled model with trt version 7.1.3.0

**Comment by sunanlin13174** [comment]
hi,SeanAvery,i meets the same problem, my jetpack is 4.4, and tensorRT may be 7.1.3.0,i run this demo.py ,and got the same error,  did i  do some things wrong?

**Comment by sunanlin13174** [comment]
yes , my tensorRT verson is 7.1.3.0 ,and i try it in jetson xavier nx devices

**Comment by sunanlin13174** [comment]
@SeanAvery

**Comment by sunanlin13174** [comment]
@SeanAvery ,Thanks you for your quick reply. Your work is very useful for me to learn how to use python-tensorRT. Frist,i checked my environment of running,and then i followed your readme file to run demo.py .The error messages is as follows:

`/usr/bin/python3.6 /home/qyg/Desktop/yolov5-tensorrt-master/python/lib/demo.py
trtbin /home/qyg/Desktop/yolov5-tensorrt-master/python/lib/models/yolov5s-simple-32.trt
[TensorRT] ERROR: INVALID_CONFIG: The engine plan file is generated on an incompatible device, expecting compute 7.2 got compute 5.3, please rebuild.
[TensorRT] ERROR: engine.cpp (1546) - Serialization Error in deserialize: 0 (Core engine deserialization failure)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "/home/qyg/Desktop/yolov5-tensorrt-master/python/lib/demo.py", line 49, in <module>
    main()   
  File "/home/qyg/Desktop/yolov5-tensorrt-master/python/lib/demo.py", line 21, in main
    processor = Processor(model=args['model'])
  File "/home/qyg/Desktop/yolov5-tensorrt-master/python/lib/Processor.py", line 19, in __init__
    self.context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

Process finished with exit code 1
`

**Comment by sunanlin13174** [comment]
i also meets another little problem. i just run export_tensorrt.py in jetson xavier nx devices,and i got this meassages:

`[TensorRT] VERBOSE: *************** Autotuning format combination: Float(1,320,102400,3276800) -> Float(1,320,102400,3276800) ***************
[TensorRT] ERROR: /home/jenkins/workspace/TensorRT/helpers/rel-7.1/L1_Nightly_Internal/build/source/rtSafe/resources.h (462) - Cuda Error in loadKernel: 500 (named symbol not found)
[TensorRT] WARNING: GPU memory allocation error during getBestTactic: LeakyRelu_42
[TensorRT] VERBOSE: *************** Autotuning format combination: Float(1,320,102400:32,102400) -> Float(1,320,102400:32,102400) ***************
`
i am sorry for that brought you trouble,if you are not busy, i hope you can give me the solution.

**Comment by lnn523716** [comment]
i also meets the problem. i just run demo.py using yolov5s-simple-16.trt in jetson TX2 devices,the result is OK.But, i use yolov5s-simple-32.trt and  got this meassages:
trtbin /home/nvidia/Documents/yolov5-tensorrt-master/python/lib/models/yolov5s-simple-32.trt
[TensorRT] ERROR: INVALID_CONFIG: The engine plan file is generated on an incompatible device, expecting compute 6.2 got compute 5.3, please rebuild.
[TensorRT] ERROR: engine.cpp (1546) - Serialization Error in deserialize: 0 (Core engine deserialization failure)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "demo_video.py", line 37, in <module>
    main()
  File "demo_video.py", line 15, in main
    processor = Processor(model='yolov5s-simple-32.trt')
  File "/home/nvidia/Documents/yolov5-tensorrt-master/python/lib/Processor.py", line 19, in __init__
    self.context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

**Comment by naotar** [comment]
It is interesting that we are in 2021 and this error still exists with latest downloads and model. 

AttributeErrorTraceback (most recent call last)
<ipython-input-1-80b185ed0c07> in <module>
      1 from jetbot import ObjectDetector
      2 
----> 3 model = ObjectDetector('saved_model.pb')

/usr/local/lib/python3.6/dist-packages/jetbot-0.4.3-py3.6.egg/jetbot/object_detection.py in __init__(self, engine_path, preprocess_fn)
     27         load_plugins()
     28         self.trt_model = TRTModel(engine_path, input_names=[TRT_INPUT_NAME],
---> 29                                   output_names=[TRT_OUTPUT_NAME, TRT_OUTPUT_NAME + '_1'])
     30         self.preprocess_fn = preprocess_fn
     31 

/usr/local/lib/python3.6/dist-packages/jetbot-0.4.3-py3.6.egg/jetbot/tensorrt_model.py in __init__(self, engine_path, input_names, output_names, final_shapes)
     57         with open(engine_path, 'rb') as f:
     58             self.engine = self.runtime.deserialize_cuda_engine(f.read())
---> 59         self.context = self.engine.create_execution_context()
     60 
     61         if input_names is None:

AttributeError: 'NoneType' object has no attribute 'create_execution_context'
