### ISSUE TITLE
[TensorRT] ERROR: coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)

### ISSUE THREAD

**Issue by Yang-Changhui** [SeanAvery/yolov5-tensorrt#7]
I hope you can tell what is the tensorrt's version.
The folllwing is my running wrong.

[TensorRT] ERROR: coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "demo.py", line 51, in <module>
    main()
  File "demo.py", line 23, in main
    processor = Processor(model=args['model'])
  File "/home/boyt/tensorrt-onnx/lib/Processor.py", line 19, in __init__
    self.context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

**Comment by SeanAvery** [comment]
hey @Yang-Changhui, thanks for reaching out with this issue. Tried things out on the latest stable Jetpack OS and am getting the same error.

This is due to the compiled `trt` file coming from TRT version 6 instead of the latest 7 version.

You can try recompiling model.

Will update to fix this issue soon. cheers!

**Comment by SeanAvery** [comment]
uploaded new compiled model with trt version 7.1.3.0
